---
name: "PHTunnel"
version: 1.0.0
slug: phtunnel_addon
description: "Add-on version of PHTunnel(Oray HSK client)."
url: "https://github.com/shisaru292/homeassistant-phtunnel-addon"

arch:
  - aarch64
init: false
boot: "auto"
startup: "services"
